apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: order
  endpoints:
  - port: http
    path: /metrics
    interval: 10s