apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: blue
  template:
    metadata:
      labels:
        app: product
        version: blue
    spec:
      containers:
        - name: product
          image: musthafa110/product-service:blue
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
