apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: product
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
