apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
    version: green  # Change to blue when switching
  ports:
    - name: http-metrics
      protocol: TCP
      port: 80
      targetPort: 80
