apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
